Fixed: Description for Dehydrated Carps
Simyon264/Suspicion-on-Space-Station pull request #11
Opened 2024-10-21 14:11 UTC by Coolsurf6

## About the PR
Locales don't work on entity descriptions, fixed some wording as well

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
N/A

**Changelog**
:cl:
- fix: Dehydrated Carp Description is functional now

2024-10-21 16:04 UTC, Coolsurf6 commented
Mind role entities are failing. Completely unsure why...

2024-10-21 16:42 UTC, Simyon264 requested changes
sus

2024-10-21 16:42 UTC, Simyon264 commented on Resources/Prototypes/_SSS/Objects/store_items.yml
> +  description: Box filled with 4 dehydrated carps. Make sure your friends pet them as well!
The way its currently set up, this will ignore `uplink-carp-box-desc` set in the .ftl file.
```suggestion
  description: uplink-carp-box-desc
```

2024-10-21 23:14 UTC, Coolsurf6 commented on Resources/Prototypes/_SSS/Objects/store_items.yml
> +  description: Box filled with 4 dehydrated carps. Make sure your friends pet them as well!
The item itself seems to completely ignore the locale file. It is only ever parsed for stuff like the traitor uplink menu. Not the object itself. If you check in game, the description of the entity is literally just "uplink-carp-box-desc"

2024-10-22 03:09 UTC, Simyon264 commented on Resources/Prototypes/_SSS/Objects/store_items.yml
> +  description: Box filled with 4 dehydrated carps. Make sure your friends pet them as well!
Alright

2024-10-22 03:09 UTC, merged