Health bar
Simyon264/Suspicion-on-Space-Station pull request #13
Opened 2024-10-21 23:11 UTC by Callmore

IT'S A HEALTH BAR HOLY SHID

## About the PR

## Why / Balance

## Technical details

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Status UI showing health, role and timer.

2024-10-21 23:13 UTC, Callmore commented
wait hold on i forgor to add it to default hud

2024-10-21 23:13 UTC, Callmore commented
also @Simyon264 please actually make sure it works thanks

2024-10-21 23:16 UTC, Coolsurf6 commented
Wait actually how huge is this, WE NEED MEDIIIAAAA

2024-10-22 06:32 UTC, Simyon264 commented
![image](https://github.com/user-attachments/assets/0881afe3-d255-45dd-b327-a691b6657817)
Testing this locally, the timer seems to not update correctly once the round starts?

2024-10-22 11:26 UTC, Simyon264 requested changes
very sus and very cool

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +    private ISawmill _log = default!;
I would prefer this to be spaced out some more. Preferably below the UI system dependencies.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        _log.Info($"{nameof(SSSStatusUIController)} loaded.");
Make this a debug log

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +            SetHealthBarCustom("DEAD", 0, 100);
Localize this string.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        // var hp = Math.Max((maxHp - ent.Comp.TotalDamage).Float(), 0);
Commented out?

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        SetHealthBarCustom($"\u2665 {hp}", hp, maxHp);
Localize this too.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        _log.Info($"WHAT AT {ev.EndTime}");
Make this debug too, preferably also more descriptive of what is being logged?

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        SetRoleCustom("Preround", Color.DarkGray);
Localize this string too.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        SetRoleCustom("Preround", Color.DarkGray);
Localize this string too.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        SetRoleCustom("Obserbing", Color.DarkGray);
Localize this string too.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/SSSStatusUIController.cs
> +        // ui.RoleText.Text = ev.NewRole.ToString();
This is also commented out, just remove if its not needed.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Client/_SSS/UserInterface/Widgets/SSSStatusGui.xaml
> +    <Control>
Remove commented out code.

2024-10-22 11:26 UTC, Simyon264 commented on Content.Server/_SSS/SuspicionGameRule/SuspicionRuleSystem.Spawning.cs
> +    [Dependency] private readonly GameTicker _gameTicker = default!;
Put this dependency with the other dependencies in SuspicionRuleSystem.cs

2024-10-24 07:11 UTC, Simyon264 commented
Lets go try this

2024-10-24 07:11 UTC, merged